### ISSUE TITLE
using namespaces

### ISSUE THREAD

**Issue by isidromerayo** [hafriedlander/phockito#1]
Hi, I try to create a mock object using namespace

$this->screen = Phockito::mock('\com\holatdd\Screen');

but have a error message

PHP Parse error:  syntax error, unexpected T_NS_SEPARATOR, expecting '{' in /usr/share/php/phockito/Phockito.php(256) : eval()'d code on line 1
PHP Fatal error:  Class '__phockito_\com\holatdd\Screen_Mock' not found in /usr/share/php/phockito/Phockito.php on line 287

Thanks!

Sorry my poor english

  Isidro

**Comment by joelsonoda** [comment]
Have you tried escaping your slashes?
$this->screen = Phockito::mock('\com\holatdd\Screen');

**Comment by dagguh** [comment]
You can use my branch in the meantime: https://github.com/dagguh/phockito
It supports namespaces, e.g.:
mock('\\com\\holatdd\\Screen');

It also supports Type Hinting.

**Comment by isidromerayo** [comment]
Thanks!!!

**Comment by hafriedlander** [comment]
I've just added a modified version of @dagguh's patch to master which adds support for namespaces. Let me know if you still have issues

(I'm just working on adding type hinting support now, so if you were relying on that from @dagguh's branch, worth waiting a couple of hours)
