### ISSUE TITLE
SS manifest overloading won't work with 3.1

### ISSUE THREAD

**Issue by chillu** [hafriedlander/phockito#12]
PhockitoSilverStripe and PhockitoSilverStripeTest. I'm not even sure _what_ it does, but I'm pretty sure whatever it is won't work in 3.1 due to the changed way of persisting the manifest ;)

**Comment by hafriedlander** [comment]
Fixed in hafriedlander/silverstripe-phockito. Composer makes dependancies easy, so just use that module rather than this one directly with SilverStripe
