### ISSUE TITLE
Spies seem to have reserved words for arguments.

### ISSUE THREAD

**Issue by passthefist** [hafriedlander/phockito#22]
This is a generated method for a spy:

``` php
public function myMethod( $request, $response ){
    $args = func_get_args();

    $backtrace = debug_backtrace();
    $instance = $backtrace[0]['type'] == '::' ? ('::'.'tag_test_mocks_routing_controller') : $this->__phockito_instanceid;

    // The value for $response that was passed to the method is
    // now replaced by this value for $response.
    $response = \Phockito::__called('tag_test_mocks_routing_controller', $instance, 'myMethod', $args);

    if ($response) return \Phockito::__perform_response($response, $args);
    else return parent::myMethod( $request, $response );
  }
```

Because $backtrace, $instance, $response, and $args are all assigned in this method, if used as function parameters, then the value passed to the method is invisibly replaced by the value in this function.

This means for full functionality with phockito, functions should not take any of those as arguments. The 'bug' manifests itself as function parameters mysteriously becoming null when the function is called on a spy, even though the value passed to the function is non-null. This occurs if no stub/responder has been set for the spy.

Normally I'd submit a pull request with a fix but I'm not actually sure the best way to fix this, since obfuscating the variable names has the same problem, plus makes the code unreadable.

And using call_user_func() seemed to have issues resolving parent when I tried.

**Comment by hafriedlander** [comment]
Ah, good point. `__phockito` is unofficially reserved as a variable prepend, so `$__phockito_response` is OK, but not very pretty.

As far as using `call_user_func` instead, you can't use `parent` in `call_user_func`, but we already know what the parent type is in `$mockedClass`, so `array($mockedClassString, "{$method->name}")` should work as a callable.

I might have a look in a bit if you don't get a chance.

**Comment by hafriedlander** [comment]
Fixed in https://github.com/hafriedlander/phockito/commit/6e03920c93f054f9e0c220c3c607048a304b88d5

**Comment by passthefist** [comment]
Lol, I was just writing a response now. Nice turn around there. Thanks.

**Comment by hafriedlander** [comment]
I just happened to be working on Phockito now. You can probably tell by the age of the other issues I'm not always that prompt, so don't get used to it :P
