### ISSUE TITLE
Type Hinting

### ISSUE THREAD

**Issue by dagguh** [hafriedlander/phockito#3]
About type hinting in PHP: http://www.php.net/manual/en/language.oop5.typehinting.php

Classes with type-hinted methods cannot be mocked.

Code:

``` php
<?
Phockito::mock("Foo");

class Foo {

    public function doStuff(Bar $bar) {
    }
}

class Bar {
}
```

results in:
Fatal error: Declaration of  __phockito_Foo_Mock must be compatible with that of Foo in (...)

**Comment by dagguh** [comment]
I have found a way to fix this, but I think I need to wait until my Pull Request is merged.

**Comment by hafriedlander** [comment]
Hi. Thanks for the pull request. I've rewritten your patch slightly & merged a fix into master.
